version: '3.8'

services:
  resume-relevance-app:
    build: .
    ports:
      - "8003:8003"  # FastAPI backend
      - "8505:8505"  # Streamlit dashboard
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./app/uploads:/app/app/uploads  # Persist uploaded files
      - ./app/data.db:/app/app/data.db  # Persist database
    restart: unless-stopped
    container_name: resume-relevance-system

networks:
  default:
    name: resume-relevance-network