# Streamlit Cloud Secrets Template
# Copy this file to your Streamlit Cloud app settings under "Secrets"

[general]
GEMINI_API_KEY = "your_gemini_api_key_here"

# Optional: Custom API endpoints
# API_BASE_URL = "custom_backend_url"